PATCH http://localhost:5000/api/v1/items/1
content-type: application/json

{
    "name": "sample8",
    "cost": 10000000000000000000000000000000000000
}

http://localhost:5000/api/v1/auth/

POST http://localhost:5000/api/v1/accounts
content-type: application/json
authorization: Bearer sometoken

{
    "username": "adnan346fj",
    "password" : "adnan124A!",
    "email": "adnan.ka5mifli3j4@gmail.com",
    "name": "Adnan Kamili",
    "company": "Adnan Kamili"
}

GET http://localhost:5000/api/v1/items/1
authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IlZTXzZSWUpUV1NYTS1MUzZVV1BFUE1FNzRJWTFQRjI2SkRFUVU1RkciLCJ0eXAiOiJKV1QifQ.eyJ1bmlxdWVfbmFtZSI6ImFkbmFuLmthbWlsaUBnbWFpbC5jb20iLCJBc3BOZXQuSWRlbnRpdHkuU2VjdXJpdHlTdGFtcCI6IjRiOWU2YWM5LTQ2ZDEtNDViNi1hMDMwLWIwMGE4YzFhOTIwYiIsImp0aSI6IjFmYjgzMmU1LWIwM2QtNDU0OS1hNTU3LWEyZmMxYjlkYWNjMyIsInVzYWdlIjoiYWNjZXNzX3Rva2VuIiwic2NvcGUiOiJvcGVuaWQiLCJzdWIiOiI5N2IzOTE5Zi05ZjAxLTQzYTgtOTE4OC0yZDE5NzU2NThiZjgiLCJuYmYiOjE0ODQ3MjUxMDgsImV4cCI6MTQ4NDcyNjkwOCwiaWF0IjoxNDg0NzI1MTA4LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAvIn0.iv1QxdC7LIYDTlcM551gn8PDGueBKrAgB3rSffYk9ICdW4sp_FvnXhRyUMbftviWIY7_f4B9kybRZxiZ4zq_fmmI2-LtyZHeSF-MqpWWaEsGxZojQocg3RuHk-hE_MvzzXkOLyfXGnmyhMSiOJHv36KXzzQyktPYgvwBE7fa_seAUIc3v72LLZKX83VSY_HZvZ7g2SwNU50EtVMJYBA5s9kAc3VgIfw-X4B7PHecLQBaHHgYoUgM01k_7G9pXWAvlLDc_r48DFmDCTEogI0apTDDnSstAzJ8XW9trICEokNEgfpLr8njezXQscaHnw7RT4EMeB4XcVrvXkAzxuXWdQ