PATCH http://localhost:5000/api/v1/items/1
content-type: application/json

{
    "name": "sample8",
    "cost": 10000000000000000000000000000000000000
}

http://localhost:5000/api/v1/auth/

POST http://localhost:5000/api/v1/accounts
content-type: application/json
authorization: Bearer sometoken

{
    "username": "adnan.kamili_role@gmail.com",
    "password" : "adnan124A!",
    "email": "adnan.kamili_role_email@gmail.com",
    "name": "Adnan Kamili",
    "company": "Adnan Kamili"
}

GET http://localhost:5000/api/v1/items/1
authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Ik5aR1NSNVU3VEpaV0I2WFUtS1UtS0xBMzFISDFJNVlLS0szT1JYUkgiLCJ0eXAiOiJKV1QifQ.eyJ1bmlxdWVfbmFtZSI6ImFkbmFuLmthbWlsaUBnbWFpbC5jb20iLCJBc3BOZXQuSWRlbnRpdHkuU2VjdXJpdHlTdGFtcCI6IjRiOWU2YWM5LTQ2ZDEtNDViNi1hMDMwLWIwMGE4YzFhOTIwYiIsImp0aSI6ImQyNWMxOTlmLTgxNzQtNDMyOC04N2M0LWMzMzFmNDRkNWViYiIsInVzYWdlIjoiYWNjZXNzX3Rva2VuIiwic2NvcGUiOiJvcGVuaWQiLCJzdWIiOiI5N2IzOTE5Zi05ZjAxLTQzYTgtOTE4OC0yZDE5NzU2NThiZjgiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJuYmYiOjE0ODUxNjg5NjYsImV4cCI6MTQ4NTE3MDc2NiwiaWF0IjoxNDg1MTY4OTY2LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAvIn0.NFUQ9E9QHZY_CnbpMV63aaqOLFhYh4XXON9Dw7aQXYiqTZtgcQzaXLa_A6KDCwwnbUV0eEcaQqZlUSLmjXyKtTxlDtZqIGiIU601LyjoyeXn7pKN-XW4bGlDjyJ5JT1k6SCWuXWo1FDPcfy22yCWPEa32CGIyrySUmtcDsb7czKqPTW6FMTGgVi6t7FnraY53Cr4m1KKJ4BLXI6CwlI4d7ku6famLQMg7m5pwajUTThYN6jsjls7o4vejyEhjE-CT08_ZfwAsvs-Sc6-RPjNhOXywfescGdBNL8lIPy1nLurGCC3AMq3o4AKB5DXgt8odWL-1yLA7t6LRDkp41YIYQ